### Salmon microbiome project
### Code generated by Bingdi Liu (bliu28@wustl.edu) and Kara Andres (akara@wustl.edu)
### This code accomplishes the correlation between technical replicates
# cor after basic denoising and before decontam for all samples(including negatives)
# but we only report the cor result for salmon samples (no negatives)
# pearson correlation -- https://towardsdatascience.com/covariance-and-correlation-321fdacab168

load("salmon_before_decontam.RDATA")
salmon_nontree_m.ReAb <- transform_sample_counts(salmon_nontree_m, function(OTU) OTU/sum(OTU))
Pearson_cor_table <- as.data.frame(cor(salmon_nontree_m.ReAb@otu_table, use="all.obs", method="pearson"))

keeep <- sort(colnames(Pearson_cor_table))
Pearson_cor_table_srt <- Pearson_cor_table[,keeep]
Pearson_cor_table_srt <- Pearson_cor_table_srt[order(row.names(Pearson_cor_table_srt)), ]
df <- data.frame(Samplename=rep(0,64),Pearson_values=rep(0,64))
number_index <- seq(1,64,by=2)
for(i in number_index){
  df[i,2] <- Pearson_cor_table_srt[i,i+1]
}
df$Samplename <- rownames(Pearson_cor_table_srt)
peason_table <- df[df$Pearson_values>0,]
peason_table$new_samplename <- str_split(peason_table$Samplename,"_",simplify = TRUE)[1:32]
peason_table$index_sort <- str_split(peason_table$new_samplename,"-",simplify = TRUE)[1:32,2]
#sample_table from nextlines
sample_table_pearson <- data.frame(sample_table)
sample_table_pearson$index_sort <- str_split(sample_table_pearson$fish_ID,"-",simplify = TRUE)[1:30,2]
sample_table_pearson$index_sort <- as.double(sample_table_pearson$index_sort)

sample_data(salmon_nontree_m)[,c("fish_ID","fish_type","hatchery","BKD_vaccinated")]
sample_table <- unique(sample_data(salmon_nontree_m)[,c("fish_ID","fish_type","hatchery","BKD_vaccinated")])
rownames(sample_table) <- sample_table$fish_ID

