### Salmon microbiome project
### Code generated by Bingdi Liu (bliu28@wustl.edu) and Kara Andres (akara@wustl.edu)
### This code accomplishes the data analysis and graphical presentation of data

#### Clear the working environment and load required packages
rm(list = ls())
library(vegan)
library(phyloseq)
library(xlsx)
library(reshape2)
library(ggplot2)
library(colorspace)
library(scales)
library(dplyr)
library(Biostrings)
library(stringr)
library(tidyverse)
library(ggrepel)
library(phylosmith)
library(ggpubr)
library(gghalves)
library(writexl)
library(forcats)
library(RColorBrewer)
library(viridis)
library(lefser)
library(DESeq2)
library(rstatix)
theme_set(theme_bw())

### Load dataset 
load("normld_salmon.RDATA")
normld_salmon.ReAb <- transform_sample_counts(normld_salmon, function(OTU) OTU*100/sum(OTU))
# write.csv(normld_salmon.ReAb@tax_table, "tax_table.csv")
# Add combined life state/vaccination to sample data
normld_salmon.ReAb@sam_data$combined <- with(normld_salmon.ReAb@sam_data, paste0(fish_type, "_", BKD_vaccinated, "_", hatchery))

################################################################################################
#################### Phylum-level breakdown ####################################################
################################################################################################

### All samples
normld_salmon.ReAb.all <- prune_taxa(taxa_sums(normld_salmon.ReAb)>0, normld_salmon.ReAb)
names_unknown <- taxa_names(normld_salmon.ReAb.all@tax_table)[is.na(normld_salmon.ReAb.all@tax_table[,"Phylum"])]
normld_salmon.ReAb.all@tax_table[is.na(normld_salmon.ReAb.all@tax_table[,"Phylum"]),"Phylum"] <- c("unclassified Phyla")
normld_salmon.ReAb.all <- tax_glom(normld_salmon.ReAb.all, NArm=FALSE, taxrank="Phylum")
names_unknown <- taxa_names(normld_salmon.ReAb.all@tax_table)[normld_salmon.ReAb.all@tax_table[,"Phylum"]=="unclassified Phyla"]
names_others <- taxa_names(normld_salmon.ReAb.all@tax_table[taxa_sums(normld_salmon.ReAb.all)< 0.1|taxa_sums(normld_salmon.ReAb.all)==0.1,])
names_others <- names_others[is.na(match(names_others,names_unknown))]
normld_salmon.ReAb.all@tax_table[names_others,"Phylum"] <- c("Other_Phyla")
taxatable <- as.data.frame(normld_salmon.ReAb.all@tax_table[,"Phylum"])
taxatable$OTUname <- rownames(taxatable)
otutable <- as.data.frame(t(as.data.frame(normld_salmon.ReAb.all@otu_table)))
otutable$otuname <- rownames(otutable)
taxotutable <- merge(taxatable,otutable, by.x="OTUname", by.y="otuname")
taxotutable <- taxotutable[,c(2:ncol(taxotutable))]
Pgroup <- taxotutable$Phylum
ReAb <- rowsum(taxotutable[,c(2:ncol(taxotutable))],Pgroup)
ReAb$Phylum <- rownames(ReAb)

### accumulation curves
accum.cols <- c(brewer.pal(8, "Dark2"))
normld_salmon@sam_data$combined <- with(normld_salmon@sam_data, paste0(fish_type, "_", BKD_vaccinated, "_", hatchery))
normld_salmon.sac <- prune_taxa(taxa_sums(normld_salmon)>10,normld_salmon)
normld_salmon.Juvenile_N_LSSU <- subset_samples(normld_salmon,combined=="Juvenile_N_LSSU")
normld_salmon.Juvenile_Y_LSSU <- subset_samples(normld_salmon,combined=="Juvenile_Y_LSSU")
normld_salmon.Adult_N_LSSU <- subset_samples(normld_salmon,combined=="Adult_N_LSSU")
normld_salmon.Adult_N_DNR <- subset_samples(normld_salmon,combined=="Adult_N_DNR")
plot(specaccum(normld_salmon.sac@otu_table), ci.type="poly", 
     col=accum.cols[1], lwd=4, ci.lty=0, ci.col=alpha(accum.cols[1], 0.2), xlab="Samples", ylab="# of ASVs",
     cex.axis=1.5, cex.lab=1.5, ylim = c(0,700))
legend(20, 200, legend=c("All samples","Unvaccinated juveniles (n=10)","Vaccinated juveniles (n=9)",
                         "LSSU Adults (n=9)","DNR Adults (n=9)"), col=accum.cols[c(1,3,4,5,6)], lwd=4, bty="n")
plot(specaccum(normld_salmon.Juvenile_N_LSSU@otu_table), ci.type="poly", 
     col=accum.cols[3], lwd=4, ci.lty=0, ci.col=alpha(accum.cols[3], 0.2), add=T)
plot(specaccum(normld_salmon.Juvenile_Y_LSSU@otu_table), ci.type="poly", 
     col=accum.cols[4], lwd=4, ci.lty=0, ci.col=alpha(accum.cols[4], 0.2), add=T)
plot(specaccum(normld_salmon.Adult_N_LSSU@otu_table), ci.type="poly", 
     col=accum.cols[5], lwd=4, ci.lty=0, ci.col=alpha(accum.cols[5], 0.2), add=T)
plot(specaccum(normld_salmon.Adult_N_DNR@otu_table), ci.type="poly", 
     col=accum.cols[6], lwd=4, ci.lty=0, ci.col=alpha(accum.cols[6], 0.2), add=T)

my.cols <- c(brewer.pal(8,"Dark2")[-c(2,5)], "#C46254","bisque","darkorange", rainbow_hcl(5), rainbow(5), "azure3")
base.phylum <- normld_salmon.ReAb.all %>% tax_glom(taxrank="Phylum", NArm=FALSE) %>% psmelt()
plot1 <- ggplot(base.phylum, aes(x=fish_ID, y=Abundance, fill=fct_reorder(Phylum, Abundance, .desc=TRUE))) + 
  geom_bar(stat="identity", position="stack") +
  facet_wrap(~combined, scales="free_x", nrow=1, ncol=4) +
  scale_fill_manual(name="Phylum", values=my.cols) +
  scale_color_manual(name="Phylum", values=my.cols) +
  ylab("Relative Abundance (%)") + xlab("Sample ID") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
plot1
# ggsave("Figures/RelAbund_barplot_all_samples.pdf", plot=plot1)

### Sub-adults
normld_salmon.ReAb.Juvenile <- subset_samples(normld_salmon.ReAb.all,fish_type=="Juvenile")

### Vaccinated juveniles
normld_salmon.ReAb.Juvenile.Vac <- subset_samples(normld_salmon.ReAb.Juvenile,BKD_vaccinated=="Y")
taxatable.Juveniles.Vac <- as.data.frame(normld_salmon.ReAb.Juvenile.Vac@tax_table[,"Phylum"])
taxatable.Juveniles.Vac$OTUname <- rownames(taxatable.Juveniles.Vac)
otutable.Juveniles.Vac <- as.data.frame(t(as.data.frame(normld_salmon.ReAb.Juvenile.Vac@otu_table)))
otutable.Juveniles.Vac$otuname <- rownames(otutable.Juveniles.Vac)
taxotutable.Juveniles.Vac <- merge(taxatable.Juveniles.Vac,otutable.Juveniles.Vac, by.x="OTUname", by.y="otuname")
taxotutable.Juveniles.Vac <- taxotutable.Juveniles.Vac[,c(2:ncol(taxotutable.Juveniles.Vac))]
Pgroup <- taxotutable.Juveniles.Vac$Phylum
ReAb_J_V <- rowsum(taxotutable.Juveniles.Vac[,c(2:ncol(taxotutable.Juveniles.Vac))],Pgroup)
ReAb_J_V$J_V_mReAb <- rowMeans(ReAb_J_V)
ReAb_J_V$Phylum_J_V <- rownames(ReAb_J_V)
ReAb_J_V$J_V_SD <- apply(ReAb_J_V[,1:(ncol(ReAb_J_V)-2)],1,sd)

### Unnvaccinated sub-adults
normld_salmon.ReAb.Juvenile.UnVac <- subset_samples(normld_salmon.ReAb.Juvenile,BKD_vaccinated=="N")
taxatable.Juveniles.UnVac <- as.data.frame(normld_salmon.ReAb.Juvenile.UnVac@tax_table[,"Phylum"])
taxatable.Juveniles.UnVac$OTUname <- rownames(taxatable.Juveniles.UnVac)
otutable.Juveniles.UnVac <- as.data.frame(t(as.data.frame(normld_salmon.ReAb.Juvenile.UnVac@otu_table)))
otutable.Juveniles.UnVac$otuname <- rownames(otutable.Juveniles.UnVac)
taxotutable.Juveniles.UnVac <- merge(taxatable.Juveniles.UnVac,otutable.Juveniles.UnVac, by.x="OTUname", by.y="otuname")
taxotutable.Juveniles.UnVac <- taxotutable.Juveniles.UnVac[,c(2:ncol(taxotutable.Juveniles.UnVac))]
Pgroup <- taxotutable.Juveniles.UnVac$Phylum
ReAb_J_UV <- rowsum(taxotutable.Juveniles.UnVac[,c(2:ncol(taxotutable.Juveniles.UnVac))],Pgroup)
ReAb_J_UV$J_UV_mReAb <- rowMeans(ReAb_J_UV)
ReAb_J_UV$Phylum_J_UV <- rownames(ReAb_J_UV)
ReAb_J_UV$J_UV_SD <- apply(ReAb_J_UV[,1:(ncol(ReAb_J_UV)-2)],1,sd)

### Adults
normld_salmon.ReAb.Adult <- subset_samples(normld_salmon.ReAb.all,fish_type=="Adult")
taxatable.Adults <- as.data.frame(normld_salmon.ReAb.Adult@tax_table[,"Phylum"])
taxatable.Adults$OTUname <- rownames(taxatable.Adults)
otutable.Adults <- as.data.frame(t(as.data.frame(normld_salmon.ReAb.Adult@otu_table)))
otutable.Adults$otuname <- rownames(otutable.Adults)
taxotutable.Adults <- merge(taxatable.Adults,otutable.Adults, by.x="OTUname", by.y="otuname")
taxotutable.Adults <- taxotutable.Adults[,c(2:ncol(taxotutable.Adults))]
Pgroup <- taxotutable.Adults$Phylum
ReAb_A <- rowsum(taxotutable.Adults[,c(2:ncol(taxotutable.Adults))],Pgroup)
ReAb_A$A_mReAb <- rowMeans(ReAb_A)
ReAb_A$Phylum_A <- rownames(ReAb_A)
ReAb_A$A_SD <- apply(ReAb_A[,1:(ncol(ReAb_A)-2)],1,sd)

# DNR
normld_salmon.ReAb.Adult <- subset_samples(normld_salmon.ReAb.all,fish_type=="Adult")
normld_salmon.ReAb.Adult.DNR <- subset_samples(normld_salmon.ReAb.Adult,hatchery=="DNR")
taxatable.Adults <- as.data.frame(normld_salmon.ReAb.Adult.DNR@tax_table[,"Phylum"])
taxatable.Adults$OTUname <- rownames(taxatable.Adults)
otutable.Adults <- as.data.frame(t(as.data.frame(normld_salmon.ReAb.Adult.DNR@otu_table)))
otutable.Adults$otuname <- rownames(otutable.Adults)
taxotutable.Adults <- merge(taxatable.Adults,otutable.Adults, by.x="OTUname", by.y="otuname")
taxotutable.Adults <- taxotutable.Adults[,c(2:ncol(taxotutable.Adults))]
Pgroup <- taxotutable.Adults$Phylum
ReAb_A_DNR <- rowsum(taxotutable.Adults[,c(2:ncol(taxotutable.Adults))],Pgroup)
ReAb_A_DNR$A_DNR_mReAb <- rowMeans(ReAb_A_DNR)
ReAb_A_DNR$Phylum_A_DNR <- rownames(ReAb_A_DNR)
ReAb_A_DNR$A_DNR_SD <- apply(ReAb_A_DNR[,1:(ncol(ReAb_A_DNR)-2)],1,sd)

# LSSU
normld_salmon.ReAb.Adult <- subset_samples(normld_salmon.ReAb.all,fish_type=="Adult")
normld_salmon.ReAb.Adult.LSSU <- subset_samples(normld_salmon.ReAb.Adult,hatchery=="LSSU")
taxatable.Adults <- as.data.frame(normld_salmon.ReAb.Adult.LSSU@tax_table[,"Phylum"])
taxatable.Adults$OTUname <- rownames(taxatable.Adults)
otutable.Adults <- as.data.frame(t(as.data.frame(normld_salmon.ReAb.Adult.LSSU@otu_table)))
otutable.Adults$otuname <- rownames(otutable.Adults)
taxotutable.Adults <- merge(taxatable.Adults,otutable.Adults, by.x="OTUname", by.y="otuname")
taxotutable.Adults <- taxotutable.Adults[,c(2:ncol(taxotutable.Adults))]
Pgroup <- taxotutable.Adults$Phylum
ReAb_A_LSSU <- rowsum(taxotutable.Adults[,c(2:ncol(taxotutable.Adults))],Pgroup)
ReAb_A_LSSU$A_LSSU_mReAb <- rowMeans(ReAb_A_LSSU)
ReAb_A_LSSU$Phylum_A_LSSU <- rownames(ReAb_A_LSSU)
ReAb_A_LSSU$A_LSSU_SD <- apply(ReAb_A_LSSU[,1:(ncol(ReAb_A_LSSU)-2)],1,sd)

### Pie charts of major Phyla for adult and sub-adult salmon
pie_plot <- merge(ReAb_A[,c("Phylum_A","A_mReAb")], ReAb_J_UV[, c("Phylum_J_UV","J_UV_mReAb")], by.x="Phylum_A", by.y="Phylum_J_UV", all=TRUE)
pie_plot <- merge(pie_plot,ReAb_J_V[, c("Phylum_J_V","J_V_mReAb")],by.x="Phylum_A",by.y="Phylum_J_V",all=TRUE)
pie_plot <- merge(pie_plot, ReAb_A_DNR[, c("Phylum_A_DNR","A_DNR_mReAb")], by.x="Phylum_A", by.y="Phylum_A_DNR", all=TRUE)
pie_plot <- merge(pie_plot, ReAb_A_LSSU[, c("Phylum_A_LSSU","A_LSSU_mReAb")], by.x="Phylum_A", by.y="Phylum_A_LSSU", all=TRUE)
colnames(pie_plot)[1] <- c("Phylum")
pie_plot$MREAB <- rowMeans(pie_plot[,3:6],na.rm = TRUE)
pie_plot_ord <- pie_plot[order(pie_plot$MREAB,decreasing = TRUE),]
pie_plot_ord$Phylum[pie_plot_ord$Phylum=="Other_Phyla"] <- c("other Phyla")
pie_plot_ord$Phylum <- factor(pie_plot_ord$Phylum,levels=c(unique(as.character(pie_plot_ord$Phylum))))
pie_A <- ggplot(pie_plot_ord,aes(x="",y=A_mReAb,fill=Phylum)) + 
  geom_bar(width=1, stat="identity") + coord_polar("y", start=0) + 
  labs(title="Adults", size=12) + 
  theme_void() + scale_fill_manual(values=c(my.cols))
pie_A_DNR <- ggplot(pie_plot_ord,aes(x="",y=A_DNR_mReAb,fill=Phylum)) + 
  geom_bar(width=1, stat="identity") + coord_polar("y", start=0) + 
  labs(title="DNR Adults", size=12) + 
  theme_void() + scale_fill_manual(values=c(my.cols))
pie_A_LSSU <- ggplot(pie_plot_ord,aes(x="",y=A_LSSU_mReAb,fill=Phylum)) + 
  geom_bar(width=1, stat="identity") + coord_polar("y", start=0) + 
  labs(title="LSSU Adults", size=12) + 
  theme_void() + scale_fill_manual(values=c(my.cols))
pie_J_V <- ggplot(pie_plot_ord,aes(x="", y=J_V_mReAb, fill=Phylum)) + 
  geom_bar(width=1, stat="identity") + coord_polar("y", start=0) + 
  labs(title="Vaccinated sub-adults", size=12) + 
  theme_void() + scale_fill_manual(values=c(my.cols))
pie_J_UV <- ggplot(pie_plot_ord,aes(x="", y=J_UV_mReAb, fill=Phylum)) + 
  geom_bar(width=1, stat="identity") + coord_polar("y", start=0) + 
  labs(title="Unvaccinated sub-adults", size=12) + 
  theme_void() + scale_fill_manual(values=c(my.cols))

plot2 <- ggarrange(pie_A_DNR, pie_A_LSSU, pie_J_UV, pie_J_V, legend="none", nrow=1, ncol=4, align="v")
# ggsave("Figures/RelAbund_piechart.pdf", plot=plot2)

################################################################################################
################# Alpha diversity, box plots, u-test, and t-test ###########################
################################################################################################

### Diversity stats per sample
alpha_ASV_meta <- data.frame(Shannon_ASV=diversity(normld_salmon@otu_table,index="shannon"),
                              Observed_ASV=specnumber(normld_salmon@otu_table),
                              Pielou_ASV=diversity(normld_salmon@otu_table,index="shannon")/log(specnumber(normld_salmon@otu_table)),
                              Simpson_ASV=diversity(normld_salmon@otu_table,index="simp"),
                              samplenames=rownames(normld_salmon@otu_table),
                              fish_type=sample_data(normld_salmon)$fish_type,
                              hatchery=sample_data(normld_salmon)$hatchery,
                              BKD_vaccinated=sample_data(normld_salmon)$BKD_vaccinated)

# ASV, life stage
df <- as.data.frame(alpha_ASV_meta %>%
                      group_by(fish_type) %>%
                      summarise_at(vars(1:4), list(mean)))
ASV_Shannon <- ggplot(alpha_ASV_meta, aes(x=fish_type, y=Shannon_ASV, fill=fish_type)) + 
  geom_boxplot(outlier.shape=NA, outlier.colour=NA) + 
  scale_fill_manual(values=c("#56B4E9","#D55E00")) +
  geom_point(shape=16, size=2, color="gray") + 
  labs(x="Life Stage", y="Shannon diversity", size=12) + 
  theme(axis.title.x=element_blank(), axis.text=element_text(size=12))
ASV_Observed <- ggplot(alpha_ASV_meta, aes(x=fish_type, y=Observed_ASV, fill=fish_type)) + 
  geom_boxplot(outlier.shape=NA,outlier.colour = NA) +
  scale_fill_manual(values=c("#56B4E9","#D55E00")) +
  geom_point(shape=16, size=2, color="gray") + 
  labs(x="Life Stage", y="Observed richness", size=12) + 
  theme(axis.title.x=element_blank(), axis.text=element_text(size=12))
ASV_Evenness <- ggplot(alpha_ASV_meta, aes(x=fish_type, y=Pielou_ASV,fill=fish_type)) + 
  geom_boxplot(outlier.shape=NA,outlier.colour = NA) +
  scale_fill_manual(values=c("#56B4E9","#D55E00")) +
  geom_point(shape=16, size=2, color="gray") + 
  labs(x="Life Stage", y="Pielou's evenness", size=12) + 
  theme(axis.title.x=element_blank(), axis.text=element_text(size=12))
ASV_Simpson <- ggplot(alpha_ASV_meta, aes(x=fish_type, y=Simpson_ASV, fill=fish_type)) + 
  geom_boxplot(outlier.shape=NA,outlier.colour = NA) +
  scale_fill_manual(values=c("#56B4E9","#D55E00")) +
  geom_point(shape=16, size=2, color="gray") + 
  labs(x="Life Stage", y="Simpson diversity", size=12) + 
  theme(axis.title.x=element_blank(), axis.text=element_text(size=12))
plot3 <- ggarrange(ASV_Observed, ASV_Shannon, ASV_Evenness, common.legend=TRUE,
          nrow=1, ncol=3, legend="none", align="h")
# ggsave("Figures/div_metrics_life_stage.pdf", plot=plot3, width=9.0, height=3.0)

# Kruskal-Wallis Rank Sum Test of differences in alpha diversity among samples
# p-value adjusted for multiple comparisons
kruskal.test(Observed_ASV~fish_type,data=alpha_ASV_meta)
p.adjust(kruskal.test(Observed_ASV~fish_type,data=alpha_ASV_meta)$p.value, method="bonferroni",n=3)
kruskal_effsize(alpha_ASV_meta, Observed_ASV~fish_type)
kruskal.test(Shannon_ASV~fish_type,data=alpha_ASV_meta)
p.adjust(kruskal.test(Shannon_ASV~fish_type,data=alpha_ASV_meta)$p.value, method="bonferroni",n=3)
kruskal.test(Pielou_ASV~fish_type,data=alpha_ASV_meta)
p.adjust(kruskal.test(Pielou_ASV~fish_type,data=alpha_ASV_meta)$p.value, method="bonferroni",n=3)

# ASV, hatchery origin
alpha_ASV_meta_adults <- alpha_ASV_meta[alpha_ASV_meta$fish_type=="Adult",]
df <- as.data.frame(alpha_ASV_meta_adults %>%
                      group_by(hatchery) %>%
                      summarise_at(vars(1:4), list(mean)))
ASV_Shannon <- ggplot(alpha_ASV_meta_adults, aes(x=hatchery, y=Shannon_ASV,fill=hatchery)) + 
  geom_boxplot(outlier.shape=NA, outlier.colour=NA) + 
  scale_fill_manual(values=c("#56B4E9","#D55E00")) +
  geom_point(shape=16, size=2, color="gray") + 
  labs(x="Hatchery", y="Shannon diversity", size=12) + 
  theme(axis.title.x=element_blank(), axis.text=element_text(size=12))
ASV_Observed <- ggplot(alpha_ASV_meta_adults, aes(x=hatchery, y=Observed_ASV, fill=hatchery)) + 
  geom_boxplot(outlier.shape=NA,outlier.colour = NA) +
  scale_fill_manual(values=c("#56B4E9","#D55E00")) +
  geom_point(shape=16, size=2, color="gray") + 
  labs(x="Hatchery", y="Observed richness", size=12) + 
  theme(axis.title.x=element_blank(), axis.text=element_text(size=12))
ASV_Evenness <- ggplot(alpha_ASV_meta_adults, aes(x=hatchery, y=Pielou_ASV,fill=hatchery)) + 
  geom_boxplot(outlier.shape=NA,outlier.colour = NA) +
  scale_fill_manual(values=c("#56B4E9","#D55E00")) +
  geom_point(shape=16, size=2, color="gray") + 
  labs(x="Hatchery", y="Pielou's evenness", size=12) + 
  theme(axis.title.x=element_blank(), axis.text=element_text(size=12))
ASV_Simpson <- ggplot(alpha_ASV_meta_adults, aes(x=hatchery, y=Simpson_ASV, fill=hatchery)) + 
  geom_boxplot(outlier.shape=NA,outlier.colour = NA) +
  scale_fill_manual(values=c("#56B4E9","#D55E00")) +
  geom_point(shape=16, size=2, color="gray") + 
  labs(x="Hatchery", y="Simpson diversity", size=12) + 
  theme(axis.title.x=element_blank(), axis.text=element_text(size=12))
plot4 <- ggarrange(ASV_Observed, ASV_Shannon, ASV_Evenness, common.legend=TRUE,
                   nrow=1, ncol=3, legend="none", align="h", widths=c(1,1,1,1))
# ggsave("Figures/div_metrics_hatchery.pdf", plot=plot4, width=9.0, height=3.0)

# Kruskal-Wallis Rank Sum Test of differences in alpha diversity among samples
# p-value adjusted for multiple comparisons
kruskal.test(Observed_ASV~hatchery,data=alpha_ASV_meta_adults)
p.adjust(kruskal.test(Observed_ASV~hatchery,data=alpha_ASV_meta_adults)$p.value, method="bonferroni")
kruskal.test(Shannon_ASV~hatchery,data=alpha_ASV_meta_adults)
p.adjust(kruskal.test(Shannon_ASV~hatchery,data=alpha_ASV_meta_adults)$p.value, method="bonferroni")
kruskal.test(Pielou_ASV~hatchery,data=alpha_ASV_meta_adults)
p.adjust(kruskal.test(Pielou_ASV~hatchery,data=alpha_ASV_meta_adults)$p.value, method="bonferroni")

# ASV, BKD_vaccinated
alpha_ASV_meta_juveniles <- alpha_ASV_meta[alpha_ASV_meta$fish_type=="Juvenile",]
df <- as.data.frame(alpha_ASV_meta_juveniles %>%
                      group_by(BKD_vaccinated) %>%
                      summarise_at(vars(1:4), list(mean)))
ASV_Shannon <- ggplot(alpha_ASV_meta_juveniles, aes(x=BKD_vaccinated, y=Shannon_ASV,fill=BKD_vaccinated)) + 
  geom_boxplot(outlier.shape=NA, outlier.colour=NA) + 
  scale_fill_manual(values=c("#56B4E9","#D55E00")) +
  geom_point(shape=16, size=2, color="gray") + 
  labs(x="Vaccinated", y="Shannon diversity", size=12) + 
  theme(axis.title.x=element_blank(), axis.text=element_text(size=12))
ASV_Observed <- ggplot(alpha_ASV_meta_juveniles, aes(x=BKD_vaccinated, y=Observed_ASV, fill=BKD_vaccinated)) + 
  geom_boxplot(outlier.shape=NA,outlier.colour = NA) +
  scale_fill_manual(values=c("#56B4E9","#D55E00")) +
  geom_point(shape=16, size=2, color="gray") + 
  labs(x="Vaccinated", y="Observed richness",size=12) + 
  theme(axis.title.x=element_blank(), axis.text=element_text(size=12))
ASV_Evenness <- ggplot(alpha_ASV_meta_juveniles, aes(x=BKD_vaccinated, y=Pielou_ASV,fill=BKD_vaccinated)) + 
  geom_boxplot(outlier.shape=NA,outlier.colour = NA) +
  scale_fill_manual(values=c("#56B4E9","#D55E00")) +
  geom_point(shape=16, size=2, color="gray") + 
  labs(x="Vaccinated", y="Pielou's evenness", size=12) + 
  theme(axis.title.x=element_blank(), axis.text=element_text(size=12))
ASV_Simpson <- ggplot(alpha_ASV_meta_juveniles, aes(x=BKD_vaccinated, y=Simpson_ASV, fill=BKD_vaccinated)) + 
  geom_boxplot(outlier.shape=NA,outlier.colour = NA) +
  scale_fill_manual(values=c("#56B4E9","#D55E00")) +
  geom_point(shape=16, size=2, color="gray") + 
  labs(x="Vaccinated", y="Simpson diversity", size=12) + 
  theme(axis.title.x=element_blank(), axis.text=element_text(size=12))
plot5 <- ggarrange(ASV_Observed, ASV_Shannon, ASV_Evenness,
                   nrow=1, ncol=3, legend="none", align="h", widths=c(1,1,1,1))
# ggsave("Figures/div_metrics_vaccinated.pdf", plot=plot5, width=9.0, height=3.0)

# Kruskal-Wallis Rank Sum Test of differences in alpha diversity among samples
# p-value adjusted for multiple comparisons
kruskal.test(Observed_ASV~BKD_vaccinated,data=alpha_ASV_meta_juveniles)
p.adjust(kruskal.test(Observed_ASV~BKD_vaccinated,data=alpha_ASV_meta_juveniles)$p.value, method="bonferroni", n=3)
kruskal.test(Shannon_ASV~BKD_vaccinated,data=alpha_ASV_meta_juveniles)
p.adjust(kruskal.test(Shannon_ASV~BKD_vaccinated,data=alpha_ASV_meta_juveniles)$p.value, method="bonferroni", n=3)
kruskal.test(Pielou_ASV~BKD_vaccinated,data=alpha_ASV_meta_juveniles)
p.adjust(kruskal.test(Pielou_ASV~BKD_vaccinated,data=alpha_ASV_meta_juveniles)$p.value, method="bonferroni", n=3)

################################################################################################
############################# Bray Curtis PCoA #################################################
################################################################################################

# Life stage
ord.PCoA.bray <- ordinate(normld_salmon.ReAb, method="PCoA", distance="bray")
plot6 <- plot_ordination(normld_salmon.ReAb, ord.PCoA.bray, type="samples", color="combined") +
  stat_ellipse(type="norm") +
  labs(color="Life Stage") + geom_point(size=6, stroke=1, shape=1) + 
  theme(axis.text=element_text(size=12), axis.title=element_text(size=14), legend.title=element_text(size=14), legend.text=element_text(size=12), 
        legend.position = c(0.85,0.85), legend.background=element_rect(color="darkgray", size=0.2), panel.grid=element_blank()) + 
  scale_color_manual(values=c("#D55E00", "#1B9E77","#E6AB02","#56B4E9"))
plot6$layers <- plot6$layers[-1]
plot6
# ggsave("Figures/pcoa_all.pdf", plot=plot6, width=6, height=5)

### PERMANOVA
meta <- microbiome::meta(normld_salmon)
abund <- microbiome::abundances(normld_salmon)
meta_A <- meta[meta$fish_type=="Adult",]
abund_A <- abund[,colnames(abund) %in% meta_A$fish_ID]
meta_J <- meta[meta$fish_type=="Juvenile",]
abund_J <- abund[,colnames(abund) %in% meta_J$fish_ID]
adonis2(t(abund) ~ fish_type, data=meta, permutations=999, method="bray")
adonis2(t(abund_J) ~ BKD_vaccinated, data=meta_J, permutations=999, method="bray")
adonis2(t(abund_A) ~ hatchery, data=meta_A, permutations=999, method="bray")

### PERMDISP
dist_adund <- phyloseq::distance(normld_salmon, method="bray")
dist_adund_J <- phyloseq::distance(subset_samples(normld_salmon,fish_type=="Juvenile"), method="bray")
dist_adund_A <- phyloseq::distance(subset_samples(normld_salmon,fish_type=="Adult"), method="bray")
beta <- betadisper(dist_adund, meta$fish_type)
permutest(beta)
beta <- betadisper(dist_adund_J, meta_J$BKD_vaccinated)
permutest(beta)
beta <- betadisper(dist_adund_A, meta_A$hatchery)
permutest(beta)

# Vaccinated
ord.PCoA.bray <- ordinate(normld_salmon.ReAb.Juvenile, method="PCoA", distance="bray")
plot7 <- plot_ordination(normld_salmon.ReAb.Juvenile, ord.PCoA.bray, type="samples", color="BKD_vaccinated") +
  stat_ellipse(type="norm") +
  labs(color="Sub-adult BKD\nVaccination Status") + geom_point(size=4) + 
  theme(axis.text=element_text(size=12), axis.title=element_text(size=14), legend.title=element_text(size=14), legend.text=element_text(size=12), 
        legend.position = c(0.80,0.85), legend.background=element_rect(color="darkgray", size=0.2), panel.grid=element_blank()) + 
  scale_color_manual(values = c("#56B4E9","#D55E00"))
plot7
# ggsave("Figures/pcoa_vaccinated.pdf", plot=plot7, width=6, height=5)

# Hatchery 
ord.PCoA.bray <- ordinate(normld_salmon.ReAb.Adult, method="PCoA", distance="bray")
plot8 <- plot_ordination(normld_salmon.ReAb.Adult, ord.PCoA.bray, type="samples", color="hatchery") +
  stat_ellipse(type="norm") +
  labs(color="Hatchery") + geom_point(size=4) + 
  theme(axis.text=element_text(size=12), axis.title=element_text(size=14), legend.title=element_text(size=14), legend.text=element_text(size=12), 
        legend.position = c(0.9,0.9), legend.background=element_rect(color="darkgray", size=0.2), panel.grid=element_blank()) + 
  scale_color_manual(values = c("#56B4E9","#D55E00"))
plot8
# ggsave("Figures/pcoa_hatchery.pdf", plot=plot8, width=6, height=5)

#########################################################################################
############# Define core communities ###################################################
#########################################################################################

### Sub-adults
normld_salmon.Juvenile <- subset_samples(normld_salmon,fish_type=="Juvenile")
normld_salmon.Juvenile <- prune_taxa(taxa_sums(normld_salmon.Juvenile)>0, normld_salmon.Juvenile)

### Prevalence distribution: number of samples a taxon occurs in
### ASV
ASV_prevalence_Juvenile <- as.data.frame(apply(as.data.frame(t(as.data.frame(normld_salmon.Juvenile@otu_table))),1,function(x) sum(x>0)))
colnames(ASV_prevalence_Juvenile) <- c("prevalence")
ASV_prevalence_Juvenile_ord <- as.data.frame(ASV_prevalence_Juvenile[order(ASV_prevalence_Juvenile$prevalence,decreasing = TRUE),])
colnames(ASV_prevalence_Juvenile_ord) <- c("prevalence")
countASVs_prevalence_Juvenile <- as.data.frame(table(ASV_prevalence_Juvenile_ord))
colnames(countASVs_prevalence_Juvenile) <- c("prevalence","frequency")
ASV_prevalence_Juvenile_ord$prevalence <- 100*ASV_prevalence_Juvenile_ord$prevalence/nsamples(normld_salmon.Juvenile)
J_ASV_plot <- ggplot(ASV_prevalence_Juvenile_ord,aes(prevalence)) + geom_vline(xintercept=80, linetype="dashed") +
  geom_bar()+labs(title="ASV") + scale_y_continuous(name ="Number of ASVs") + 
  scale_x_continuous(name ="Prevalence (% of samples)", limit = c(0, 100)) + 
  theme(title=element_text(size=12), legend.position="none")
J_ASV_plot

### Genus
normld_salmon.Juvenile.G <- tax_glom(normld_salmon.Juvenile, NArm=FALSE, taxrank="Genus")
G_prevalence_Juvenile <- as.data.frame(apply(as.data.frame(t(as.data.frame(normld_salmon.Juvenile.G@otu_table))), 1, function(x) sum(x>0)))
colnames(G_prevalence_Juvenile) <- c("prevalence")
G_prevalence_Juvenile_ord <- as.data.frame(G_prevalence_Juvenile[order(G_prevalence_Juvenile$prevalence,decreasing = TRUE),])
colnames(G_prevalence_Juvenile_ord) <- c("prevalence")
countGs_prevalence_Juvenile <- as.data.frame(table(G_prevalence_Juvenile_ord))
colnames(countGs_prevalence_Juvenile) <- c("prevalence","frequency")
G_prevalence_Juvenile_ord$prevalence <- 100*G_prevalence_Juvenile_ord$prevalence/nsamples(normld_salmon.Juvenile.G)
J_Genus_plot <- ggplot(G_prevalence_Juvenile_ord,aes(prevalence)) + geom_vline(xintercept=80, linetype="dashed") + 
  geom_bar()+labs(title="Genus") + scale_y_continuous(name ="Number of genera") + 
  scale_x_continuous(name ="Prevalence (% of samples)", limit = c(0, 100)) + 
  theme(title=element_text(size=12), legend.position="none")
J_Genus_plot

### Family
normld_salmon.Juvenile.F <- tax_glom(normld_salmon.Juvenile, NArm=FALSE, taxrank="Family")
F_prevalence_Juvenile <- as.data.frame(apply(as.data.frame(t(as.data.frame(normld_salmon.Juvenile.F@otu_table))), 1, function(x) sum(x>0)))
colnames(F_prevalence_Juvenile) <- c("prevalence")
F_prevalence_Juvenile_ord <- as.data.frame(F_prevalence_Juvenile[order(F_prevalence_Juvenile$prevalence,decreasing=TRUE),])
colnames(F_prevalence_Juvenile_ord) <- c("prevalence")
countFs_prevalence_Juvenile <- as.data.frame(table(F_prevalence_Juvenile_ord))
colnames(countFs_prevalence_Juvenile) <- c("prevalence","frequency")
F_prevalence_Juvenile_ord$prevalence <- 100*F_prevalence_Juvenile_ord$prevalence/nsamples(normld_salmon.Juvenile.F)
J_Family_plot <- ggplot(F_prevalence_Juvenile_ord,aes(prevalence)) + geom_vline(xintercept=80, linetype="dashed") + 
  geom_bar()+labs(title="Family") + scale_y_continuous(name ="Number of families") + 
  scale_x_continuous(name ="Prevalence (% of samples)", limit = c(0, 105)) + 
  theme(title=element_text(size=12), legend.position="none")
J_Family_plot

ggarrange(J_ASV_plot, J_Genus_plot, J_Family_plot, nrow=3, ncol = 1, align="v")

### Prevalence - average relative abundance

### ASV
normld_salmon.Juvenile.ReAb <- transform_sample_counts(normld_salmon.Juvenile, function(OTU) OTU*100/sum(OTU))
ASV_sumReAb_Juvenile <- as.data.frame(taxa_sums(normld_salmon.Juvenile.ReAb))
ASV_sumReAb_Juvenile$otu <- rownames(ASV_sumReAb_Juvenile)
colnames(ASV_sumReAb_Juvenile) <- c("sumReAb","otu")
ASV_sumReAb_Juvenile$mReAb <- ASV_sumReAb_Juvenile$sumReAb/nsamples(normld_salmon.Juvenile.ReAb)
ASV_prevalence_Juvenile$OTU <- rownames(ASV_prevalence_Juvenile)
ASV_prevalence_mReAb_Juvenile <- merge(ASV_prevalence_Juvenile,ASV_sumReAb_Juvenile,by.x="OTU",by.y="otu",all.x = TRUE,sort = FALSE)
ASV_prevalence_mReAb_Juvenile_ord <- ASV_prevalence_mReAb_Juvenile[order(ASV_prevalence_mReAb_Juvenile$prevalence),]
ASV_prevalence_mReAb_Juvenile_ord$prevalence <- 100*ASV_prevalence_mReAb_Juvenile_ord$prevalence/nsamples(normld_salmon.Juvenile.ReAb)
mod <- lm(mReAb ~ prevalence, data=ASV_prevalence_mReAb_Juvenile_ord)
summary(mod)$coefficient
summary(mod)$r.squared
df <- data.frame(p=c(NA,NA,NA),r=c(NA,NA,NA),row.names = c("Family","Genus","ASV"))
df[3,1] <- summary(mod)$coefficient[2,4]
df[3,2] <- summary(mod)$r.squared
ggplot(ASV_prevalence_mReAb_Juvenile_ord, aes(x=prevalence, y=mReAb)) + 
  geom_point(size=3,shape=1) + labs(x="Prevalence (% of samples)", y="Average relative abundance (%)") + 
  theme(axis.text=element_text(size=12), axis.title=element_text(size=14))

### Genus
normld_salmon.Juvenile.ReAb.G <- transform_sample_counts(normld_salmon.Juvenile.G, function(OTU) OTU*100/sum(OTU))
G_sumReAb_Juvenile <- as.data.frame(taxa_sums(normld_salmon.Juvenile.ReAb.G))
G_sumReAb_Juvenile$otuG <- rownames(G_sumReAb_Juvenile)
colnames(G_sumReAb_Juvenile) <- c("sumReAb","otuG")
G_sumReAb_Juvenile$mReAb <- G_sumReAb_Juvenile$sumReAb/nsamples(normld_salmon.Juvenile.ReAb.G)
G_prevalence_Juvenile$OTUG <- rownames(G_prevalence_Juvenile)
G_prevalence_mReAb_Juvenile <- merge(G_prevalence_Juvenile,G_sumReAb_Juvenile,by.x="OTUG",by.y="otuG",all.x = TRUE,sort = FALSE)
G_prevalence_mReAb_Juvenile_ord <- G_prevalence_mReAb_Juvenile[order(G_prevalence_mReAb_Juvenile$prevalence),]
G_prevalence_mReAb_Juvenile_ord$prevalence <- 100*G_prevalence_mReAb_Juvenile_ord$prevalence/nsamples(normld_salmon.Juvenile.ReAb.G)
mod <- lm(mReAb~prevalence,data=G_prevalence_mReAb_Juvenile_ord)
summary(mod)$coefficient
summary(mod)$r.squared
df[2,1] <- summary(mod)$coefficient[2,4]
df[2,2] <- summary(mod)$r.squared
ggplot(G_prevalence_mReAb_Juvenile_ord, aes(x=prevalence, y=mReAb)) + 
  geom_point(size=3,shape=1) + labs(x="Prevalence (% of samples)", y="Average relative abundance (%)") + 
  theme(axis.text=element_text(size=12), axis.title=element_text(size=14))

### Family
normld_salmon.Juvenile.ReAb.F <- transform_sample_counts(normld_salmon.Juvenile.F, function(OTU) OTU*100/sum(OTU))
F_sumReAb_Juvenile <- as.data.frame(taxa_sums(normld_salmon.Juvenile.ReAb.F))
F_sumReAb_Juvenile$otuF <- rownames(F_sumReAb_Juvenile)
colnames(F_sumReAb_Juvenile) <- c("sumReAb","otuF")
F_sumReAb_Juvenile$mReAb <- F_sumReAb_Juvenile$sumReAb/nsamples(normld_salmon.Juvenile.ReAb.F)
F_prevalence_Juvenile$OTUF <- rownames(F_prevalence_Juvenile)
F_prevalence_mReAb_Juvenile <- merge(F_prevalence_Juvenile,F_sumReAb_Juvenile,by.x="OTUF",by.y="otuF",all.x = TRUE,sort = FALSE)
F_prevalence_mReAb_Juvenile_ord <- F_prevalence_mReAb_Juvenile[order(F_prevalence_mReAb_Juvenile$prevalence),]
F_prevalence_mReAb_Juvenile_ord$prevalence <- 100*F_prevalence_mReAb_Juvenile_ord$prevalence/nsamples(normld_salmon.Juvenile.ReAb.F)
length(F_prevalence_mReAb_Juvenile_ord$OTUF[F_prevalence_mReAb_Juvenile_ord$prevalence>=80])
sum(normld_salmon.Juvenile.F@otu_table[,F_prevalence_mReAb_Juvenile_ord$OTUF[F_prevalence_mReAb_Juvenile_ord$prevalence>=80]])/sum(normld_salmon.Juvenile.F@otu_table)
mod <- lm(mReAb~prevalence,data=F_prevalence_mReAb_Juvenile_ord)
summary(mod)$coefficient
summary(mod)$r.squared
df[1,1] <- summary(mod)$coefficient[2,4]
df[1,2] <- summary(mod)$r.squared
ggplot(F_prevalence_mReAb_Juvenile_ord, aes(x=prevalence, y=mReAb)) + 
  geom_point(size=3,shape=1) + labs(x="Prevalence (% of samples)", y="Average relative abundance (%)") + 
  theme(axis.text=element_text(size=12), axis.title=element_text(size=14)) + xlim(0,100)

### Sub-adult core ASV/Genus/Family averageReAb bar plot with prevalence line overlaid 

### ASV
rownames(ASV_prevalence_mReAb_Juvenile_ord) <- ASV_prevalence_mReAb_Juvenile_ord$OTU
ASV_core <- ASV_prevalence_mReAb_Juvenile_ord[ASV_prevalence_mReAb_Juvenile_ord$OTU[ASV_prevalence_mReAb_Juvenile_ord$prevalence>=80],]
ASV_core_ord <- ASV_core[order(ASV_core$mReAb),]
ASV_core_taxa <- as.data.frame(normld_salmon.Juvenile.ReAb@tax_table[ASV_core_ord$OTU,])
ASV_core_taxa$otu <- rownames(ASV_core_taxa)
plot_ASVcore <- merge(ASV_core_ord,ASV_core_taxa,by.x="OTU",by.y="otu",all.x = TRUE,sort = FALSE)
# write_xlsx(plot_ASVcore,"/Users/linglab/Documents/salmon_m/table_S4C")

### Genus
rownames(G_prevalence_mReAb_Juvenile_ord) <- G_prevalence_mReAb_Juvenile_ord$OTUG
G_core <- G_prevalence_mReAb_Juvenile_ord[G_prevalence_mReAb_Juvenile_ord$OTUG[G_prevalence_mReAb_Juvenile_ord$prevalence>=80],]
G_core_ord <- G_core[order(G_core$mReAb),]
G_core_taxa <- as.data.frame(normld_salmon.Juvenile.ReAb.G@tax_table[G_core_ord$OTUG,])
G_core_taxa$classification <- rep("genus",nrow(G_core_taxa))
LL <- 1:nrow(G_core_taxa)
for(i in LL){
  if(is.na(G_core_taxa$Phylum[i])){
    G_core_taxa$classification[i] <- paste0("unclassified ","Bacteria"," lineage")
  }else{
    if(is.na(G_core_taxa$Class[i])){
      G_core_taxa$classification[i] <-  paste0("unclassified ",G_core_taxa$Phylum[i]," lineage")
    }else{
      if(is.na(G_core_taxa$Order[i])){
        G_core_taxa$classification[i] <-  paste0("unclassified ",G_core_taxa$Class[i]," lineage")
      }else{
        if(is.na(G_core_taxa$Family[i])){
          G_core_taxa$classification[i] <-  paste0("unclassified ",G_core_taxa$Order[i]," lineage")
        }else{
          if(is.na(G_core_taxa$Genus[i])){
            G_core_taxa$classification[i] <-  paste0("unclassified ",G_core_taxa$Family[i]," lineage")
          }else{
            G_core_taxa$classification[i] <- G_core_taxa$Genus[i]
          }
        }
      }
    }
  }
}
G_core_taxa$otuG <- rownames(G_core_taxa)
plot_Gcore <- merge(G_core_ord, G_core_taxa[,c("otuG","classification")], 
                    by.x="OTUG", by.y="otuG", all.x = TRUE,sort = FALSE)

### Family
rownames(F_prevalence_mReAb_Juvenile_ord) <- F_prevalence_mReAb_Juvenile_ord$OTUF
F_core <- F_prevalence_mReAb_Juvenile_ord[F_prevalence_mReAb_Juvenile_ord$OTUF[F_prevalence_mReAb_Juvenile_ord$prevalence>=80],]
F_core_ord <- F_core[order(F_core$mReAb),]
F_core_taxa <- as.data.frame(normld_salmon.Juvenile.ReAb.F@tax_table[F_core_ord$OTUF,])
F_core_taxa$classification <- rep("family",nrow(F_core_taxa))
LL <- 1:nrow(F_core_taxa)
for(i in LL){
  if(is.na(F_core_taxa$Phylum[i])){
    F_core_taxa$classification[i] <- paste0("unclassified ","Bacteria"," lineage")
  }else{
    if(is.na(F_core_taxa$Class[i])){
      F_core_taxa$classification[i] <-  paste0("unclassified ",F_core_taxa$Phylum[i]," lineage")
    }else{
      if(is.na(F_core_taxa$Order[i])){
        F_core_taxa$classification[i] <-  paste0("unclassified ",F_core_taxa$Class[i]," lineage")
      }else{
        if(is.na(F_core_taxa$Family[i])){
          F_core_taxa$classification[i] <-  paste0("unclassified ",F_core_taxa$Order[i]," lineage")
        }else{
          F_core_taxa$classification[i] <- F_core_taxa$Family[i]
        }
      }
    }
  }
}
F_core_taxa$otuF <- rownames(F_core_taxa)
plot_Fcore <- merge(F_core_ord, F_core_taxa[,c("otuF","classification")], 
                    by.x="OTUF", by.y="otuF", all.x=TRUE, sort=FALSE)
Fabund <- ggplot(plot_Fcore) + geom_bar(aes(x=reorder(classification,mReAb), 
                                  y=mReAb,color="Abundance"), stat="identity", fill="grey") +
  labs(x="Core family") + coord_flip() + scale_y_continuous(name="Average relative abundance (%)") +
  theme(legend.position="none", panel.grid.minor=element_blank(),
        axis.text.y=element_text(face="italic",size=10), axis.text.x=element_text(hjust=0,size=10)) +
  scale_color_manual(name=NULL, values=c("Abundance"="grey","Prevalence"="black","Prevalence"="black"))
Fprev <- ggplot(plot_Fcore) + geom_line(aes(x=reorder(classification, mReAb), y=prevalence, group=1)) +
  geom_point(aes(x=reorder(classification,mReAb), y=prevalence)) +
  coord_flip() + scale_y_continuous(name="Prevalence (% of samples)", limits=c(0,100)) +
  theme(legend.position="none", axis.text.y=element_blank(), panel.grid.minor=element_blank(), 
        axis.ticks.y=element_blank(), axis.title.y=element_blank())

PrevAbundJuv <- ggarrange(Fabund,Fprev, widths = c(3, 1))
# ggsave("Figures/prevalence_abund_juveniles.pdf", plot=PrevAbundJuv, width=7, height=10)



### Adult core community
normld_salmon.Adult <- subset_samples(normld_salmon,fish_type=="Adult")
normld_salmon.Adult <- prune_taxa(taxa_sums(normld_salmon.Adult)>0,normld_salmon.Adult)

###prevalence distribution
##ASV
ASV_prevalence_Adult <- as.data.frame(apply(as.data.frame(t(as.data.frame(normld_salmon.Adult@otu_table))),1,function(x) sum(x>0)))
colnames(ASV_prevalence_Adult) <- c("prevalence")
ASV_prevalence_Adult_ord <- as.data.frame(ASV_prevalence_Adult[order(ASV_prevalence_Adult$prevalence,decreasing = TRUE),])
colnames(ASV_prevalence_Adult_ord) <- c("prevalence")
countASVs_prevalence_Adult <- as.data.frame(table(ASV_prevalence_Adult_ord))
colnames(countASVs_prevalence_Adult) <- c("prevalence","frequency")
ASV_prevalence_Adult_ord$prevalence <- 100*ASV_prevalence_Adult_ord$prevalence/nsamples(normld_salmon.Adult)
A_ASV_plot <- ggplot(ASV_prevalence_Adult_ord,aes(prevalence)) + geom_vline(xintercept=80, linetype="dashed") + 
  geom_bar() + labs(title="ASV") + scale_y_continuous(name ="Number of ASVs") +
  scale_x_continuous(name ="Prevalence (% of samples)", limit = c(0, 105)) +
  theme(title =element_text(size=12), legend.position="none", )

##Genus
normld_salmon.Adult.G <- tax_glom(normld_salmon.Adult,NArm=FALSE,taxrank = "Genus")
G_prevalence_Adult <- as.data.frame(apply(as.data.frame(t(as.data.frame(normld_salmon.Adult.G@otu_table))),1,function(x) sum(x>0)))
colnames(G_prevalence_Adult) <- c("prevalence")
G_prevalence_Adult_ord <- as.data.frame(G_prevalence_Adult[order(G_prevalence_Adult$prevalence,decreasing = TRUE),])
colnames(G_prevalence_Adult_ord) <- c("prevalence")
countGs_prevalence_Adult <- as.data.frame(table(G_prevalence_Adult_ord))
colnames(countGs_prevalence_Adult) <- c("prevalence","frequency")
G_prevalence_Adult_ord$prevalence <- 100*G_prevalence_Adult_ord$prevalence/nsamples(normld_salmon.Adult.G)
A_G_plot <- ggplot(G_prevalence_Adult_ord, aes(prevalence)) + geom_vline(xintercept=80, linetype="dashed") + 
  geom_bar() + labs(title="Genus") + scale_y_continuous(name ="Number of genera") +
  scale_x_continuous(name ="Prevalence (% of samples)", limit = c(0, 105)) +
  theme(title =element_text(size=12), legend.position="none")

### Family
normld_salmon.Adult.F <- tax_glom(normld_salmon.Adult,NArm=FALSE,taxrank = "Family")
F_prevalence_Adult <- as.data.frame(apply(as.data.frame(t(as.data.frame(normld_salmon.Adult.F@otu_table))),1,function(x) sum(x>0)))
colnames(F_prevalence_Adult) <- c("prevalence")
F_prevalence_Adult_ord <- as.data.frame(F_prevalence_Adult[order(F_prevalence_Adult$prevalence,decreasing = TRUE),])
colnames(F_prevalence_Adult_ord) <- c("prevalence")
countFs_prevalence_Adult <- as.data.frame(table(F_prevalence_Adult_ord))
colnames(countFs_prevalence_Adult) <- c("prevalence","frequency")
F_prevalence_Adult_ord$prevalence <- 100*F_prevalence_Adult_ord$prevalence/nsamples(normld_salmon.Adult.F)

A_F_plot <- ggplot(F_prevalence_Adult_ord, aes(prevalence)) + geom_vline(xintercept=80, linetype="dashed") + 
  geom_bar() + labs(title="Family") + scale_y_continuous(name ="Number of families") +
  scale_x_continuous(name ="Prevalence (% of samples)", limit = c(0, 105)) +
  theme(title =element_text(size=12), legend.position="none")

PrevAdults <- ggarrange(A_ASV_plot, A_G_plot, A_F_plot, nrow=3, ncol=1,align="v")
#ggsave("Figures/prevalence_adults.pdf", plot=PrevAdults, width=4, height=10)

### Prevalence - average relative abundance
### ASV
normld_salmon.Adult.ReAb <- transform_sample_counts(normld_salmon.Adult, function(OTU) OTU*100/sum(OTU))
ASV_sumReAb_Adult <- as.data.frame(taxa_sums(normld_salmon.Adult.ReAb))
ASV_sumReAb_Adult$otu <- rownames(ASV_sumReAb_Adult)
colnames(ASV_sumReAb_Adult) <- c("sumReAb","otu")
ASV_sumReAb_Adult$mReAb <- ASV_sumReAb_Adult$sumReAb/nsamples(normld_salmon.Adult.ReAb)
ASV_prevalence_Adult$OTU <- rownames(ASV_prevalence_Adult)
ASV_prevalence_mReAb_Adult <- merge(ASV_prevalence_Adult,ASV_sumReAb_Adult,by.x="OTU",by.y="otu",all.x = TRUE,sort = FALSE)
ASV_prevalence_mReAb_Adult_ord <- ASV_prevalence_mReAb_Adult[order(ASV_prevalence_mReAb_Adult$prevalence),]
ASV_prevalence_mReAb_Adult_ord$prevalence <- 100*ASV_prevalence_mReAb_Adult_ord$prevalence/nsamples(normld_salmon.Adult.ReAb)
length(ASV_prevalence_mReAb_Adult_ord$OTU[ASV_prevalence_mReAb_Adult_ord$prevalence>=80])
signif(sum(normld_salmon.Adult@otu_table[,ASV_prevalence_mReAb_Adult_ord$OTU[ASV_prevalence_mReAb_Adult_ord$prevalence>=80]])/sum(normld_salmon.Adult@otu_table),2)
mod <- lm(mReAb~prevalence,data=ASV_prevalence_mReAb_Adult_ord)
summary(mod)$coefficient
summary(mod)$r.squared
df <- data.frame(p=c(NA,NA,NA),r=c(NA,NA,NA),row.names = c("Family","Genus","ASV"))
df[3,1] <- summary(mod)$coefficient[2,4]
df[3,2] <- summary(mod)$r.squared
ggplot(ASV_prevalence_mReAb_Adult_ord,aes(x=prevalence,y=mReAb)) +
  geom_point(size=3,shape=1) + labs(x="Prevalence (% of samples)", y="Average relative abundance (%)") +
  theme(axis.text = element_text(size=12), axis.title = element_text(size=14))

### Genus
normld_salmon.Adult.ReAb.G <- transform_sample_counts(normld_salmon.Adult.G, function(OTU) OTU*100/sum(OTU))
G_sumReAb_Adult <- as.data.frame(taxa_sums(normld_salmon.Adult.ReAb.G))
G_sumReAb_Adult$otuG <- rownames(G_sumReAb_Adult)
colnames(G_sumReAb_Adult) <- c("sumReAb","otuG")
G_sumReAb_Adult$mReAb <- G_sumReAb_Adult$sumReAb/nsamples(normld_salmon.Adult.ReAb.G)
G_prevalence_Adult$OTUG <- rownames(G_prevalence_Adult)
G_prevalence_mReAb_Adult <- merge(G_prevalence_Adult,G_sumReAb_Adult,by.x="OTUG",by.y="otuG",all.x = TRUE,sort = FALSE)
G_prevalence_mReAb_Adult_ord <- G_prevalence_mReAb_Adult[order(G_prevalence_mReAb_Adult$prevalence),]
G_prevalence_mReAb_Adult_ord$prevalence <- 100*G_prevalence_mReAb_Adult_ord$prevalence/nsamples(normld_salmon.Adult.ReAb.G)
length(G_prevalence_mReAb_Adult_ord$OTU[G_prevalence_mReAb_Adult_ord$prevalence>=80])
signif(sum(normld_salmon.Adult.G@otu_table[,G_prevalence_mReAb_Adult_ord$OTU[G_prevalence_mReAb_Adult_ord$prevalence>=80]])/sum(normld_salmon.Adult.G@otu_table),2)
mod <- lm(mReAb~prevalence,data=G_prevalence_mReAb_Adult_ord)
summary(mod)$coefficient
summary(mod)$r.squared
df[2,1] <- summary(mod)$coefficient[2,4]
df[2,2] <- summary(mod)$r.squared
ggplot(G_prevalence_mReAb_Adult_ord,aes(x=prevalence,y=mReAb)) +
  geom_point(size=3,shape=1) + labs(x="Prevalence (% of samples)", y="Average relative abundance (%)") +
  theme(axis.text = element_text(size=12), axis.title = element_text(size=14))

### Family
normld_salmon.Adult <- subset_samples(normld_salmon,fish_type=="Adult")
normld_salmon.Adult <- prune_taxa(taxa_sums(normld_salmon.Adult)>0,normld_salmon.Adult)
normld_salmon.Adult.F <- tax_glom(normld_salmon.Adult,NArm=FALSE,taxrank = "Family")
normld_salmon.Adult.ReAb.F <- transform_sample_counts(normld_salmon.Adult.F, function(OTU) OTU*100/sum(OTU))
F_sumReAb_Adult <- as.data.frame(taxa_sums(normld_salmon.Adult.ReAb.F))
F_sumReAb_Adult$otuF <- rownames(F_sumReAb_Adult)
colnames(F_sumReAb_Adult) <- c("sumReAb","otuF")
F_sumReAb_Adult$mReAb <- F_sumReAb_Adult$sumReAb/nsamples(normld_salmon.Adult.ReAb.F)
F_prevalence_Adult$OTUF <- rownames(F_prevalence_Adult)
F_prevalence_mReAb_Adult <- merge(F_prevalence_Adult,F_sumReAb_Adult,by.x="OTUF",by.y="otuF",all.x = TRUE,sort = FALSE)
F_prevalence_mReAb_Adult_ord <- F_prevalence_mReAb_Adult[order(F_prevalence_mReAb_Adult$prevalence),]
F_prevalence_mReAb_Adult_ord$prevalence <- 100*F_prevalence_mReAb_Adult_ord$prevalence/nsamples(normld_salmon.Adult.ReAb.F)
ggplot(F_prevalence_mReAb_Adult_ord,aes(x=prevalence,y=mReAb)) +
  geom_point(size=3,shape=1) + labs(x="Prevalence (% of samples)", y="Average relative abundance (%)") +
  theme(axis.text = element_text(size=12), axis.title = element_text(size=14))
length(F_prevalence_mReAb_Adult_ord$OTUF[F_prevalence_mReAb_Adult_ord$prevalence>=80])
signif(sum(normld_salmon.Adult.F@otu_table[,F_prevalence_mReAb_Adult_ord$OTUF[F_prevalence_mReAb_Adult_ord$prevalence>=80]])/sum(normld_salmon.Adult.F@otu_table),2)
mod <- lm(mReAb~prevalence,data=F_prevalence_mReAb_Adult_ord)
summary(mod)$coefficient
summary(mod)$r.squared
df[1,1] <- summary(mod)$coefficient[2,4]
df[1,2] <- summary(mod)$r.squared

### Adult core ASV/Genus/Family average ReAb bar plot with prevalence line overlaid
### ASV
rownames(ASV_prevalence_mReAb_Adult_ord) <- ASV_prevalence_mReAb_Adult_ord$OTU
ASV_core <- ASV_prevalence_mReAb_Adult_ord[ASV_prevalence_mReAb_Adult_ord$OTU[ASV_prevalence_mReAb_Adult_ord$prevalence>=80],]
ASV_core_ord <- ASV_core[order(ASV_core$mReAb),]
ASV_core_taxa <- as.data.frame(normld_salmon.Adult.ReAb@tax_table[ASV_core_ord$OTU,])
ASV_core_taxa$otu <- rownames(ASV_core_taxa)
plot_ASVcore <- merge(ASV_core_ord,ASV_core_taxa,by.x="OTU",by.y="otu",all.x = TRUE,sort = FALSE)
# write_xlsx(plot_ASVcore,"/Users/linglab/Documents/salmon_m/table_S5C")

### Genus
rownames(G_prevalence_mReAb_Adult_ord) <- G_prevalence_mReAb_Adult_ord$OTUG
G_core <- G_prevalence_mReAb_Adult_ord[G_prevalence_mReAb_Adult_ord$OTUG[G_prevalence_mReAb_Adult_ord$prevalence>=80],]
G_core_ord <- G_core[order(G_core$mReAb),]
G_core_taxa <- as.data.frame(normld_salmon.Adult.ReAb.G@tax_table[G_core_ord$OTUG,])
G_core_taxa$classification <- rep("genus",nrow(G_core_taxa))
LL <- 1:nrow(G_core_taxa)
for(i in LL){
  if(is.na(G_core_taxa$Phylum[i])){
    G_core_taxa$classification[i] <- paste0("unclassified ","Bacteria"," lineage")
  }else{
    if(is.na(G_core_taxa$Class[i])){
      G_core_taxa$classification[i] <-  paste0("unclassified ",G_core_taxa$Phylum[i]," lineage")
    }else{
      if(is.na(G_core_taxa$Order[i])){
        G_core_taxa$classification[i] <-  paste0("unclassified ",G_core_taxa$Class[i]," lineage")
      }else{
        if(is.na(G_core_taxa$Family[i])){
          G_core_taxa$classification[i] <-  paste0("unclassified ",G_core_taxa$Order[i]," lineage")
        }else{
          if(is.na(G_core_taxa$Genus[i])){
            G_core_taxa$classification[i] <-  paste0("unclassified ",G_core_taxa$Family[i]," lineage")
          }else{
            G_core_taxa$classification[i] <- G_core_taxa$Genus[i]
          }
        }
      }
    }
  }
}
G_core_taxa$otuG <- rownames(G_core_taxa)
plot_Gcore <- merge(G_core_ord,G_core_taxa[,c("otuG","classification")],by.x="OTUG",by.y="otuG",all.x = TRUE,sort = FALSE)
# write_xlsx(plot_Gcore,"/Users/linglab/Documents/salmon_m/table_S5B")

### Family
rownames(F_prevalence_mReAb_Adult_ord) <- F_prevalence_mReAb_Adult_ord$OTUF
F_core <- F_prevalence_mReAb_Adult_ord[F_prevalence_mReAb_Adult_ord$OTUF[F_prevalence_mReAb_Adult_ord$prevalence>=80],]
F_core_ord <- F_core[order(F_core$mReAb),]
F_core_taxa <- as.data.frame(normld_salmon.Adult.ReAb.F@tax_table[F_core_ord$OTUF,])
F_core_taxa$classification <- rep("family",nrow(F_core_taxa))
LL <- 1:nrow(F_core_taxa)
for(i in LL){
  if(is.na(F_core_taxa$Phylum[i])){
    F_core_taxa$classification[i] <- paste0("unclassified ","Bacteria"," lineage")
  }else{
    if(is.na(F_core_taxa$Class[i])){
      F_core_taxa$classification[i] <-  paste0("unclassified ",F_core_taxa$Phylum[i]," lineage")
    }else{
      if(is.na(F_core_taxa$Order[i])){
        F_core_taxa$classification[i] <-  paste0("unclassified ",F_core_taxa$Class[i]," lineage")
      }else{
        if(is.na(F_core_taxa$Family[i])){
          F_core_taxa$classification[i] <-  paste0("unclassified ",F_core_taxa$Order[i]," lineage")
        }else{
          F_core_taxa$classification[i] <- F_core_taxa$Family[i]
        }
      }
    }
  }
}
F_core_taxa$otuF <- rownames(F_core_taxa)
plot_Fcore <- merge(F_core_ord,F_core_taxa[,c("otuF","classification")],by.x="OTUF",by.y="otuF",all.x = TRUE,sort = FALSE)
Fabund <- ggplot(plot_Fcore) + geom_bar(aes(x=reorder(classification,mReAb), 
                                            y=mReAb,color="Abundance"), stat="identity", fill="grey") +
  labs(x="Core family") + coord_flip() + scale_y_continuous(name="Average relative\nabundance (%)") +
  theme(legend.position="none", panel.grid.minor=element_blank(),
        axis.text.y=element_text(face="italic",size=10), axis.text.x=element_text(hjust=0,size=10)) +
  scale_color_manual(name=NULL, values=c("Abundance"="grey","Prevalence"="black","Prevalence"="black"))
Fprev <- ggplot(plot_Fcore) + geom_line(aes(x=reorder(classification, mReAb), y=prevalence, group=1)) +
  geom_point(aes(x=reorder(classification,mReAb), y=prevalence)) +
  coord_flip() + scale_y_continuous(name="Prevalence\n(% of samples)", limits=c(70,100)) +
  theme(legend.position="none", axis.text.y=element_blank(), panel.grid.minor=element_blank(), 
        axis.ticks.y=element_blank(), axis.title.y=element_blank())
# write_xlsx(plot_Fcore,"/Users/linglab/Documents/salmon_m/table_S4A")
PrevAbundAd <- ggarrange(Fabund,Fprev, widths = c(4, 1))
# ggsave("Figures/prevalence_abund_adults.pdf", plot=PrevAbundAd, width=4.5, height=2)

#########################################################################################
######################## LDA biomarker analysis #########################################
#########################################################################################
library(lefser)
library(microbial)
library(mia)
library(microbiomeMarker)
library(SummarizedExperiment)

# microbiomeMarker package
mm_lefse <- run_lefse(normld_salmon, wilcoxon_cutoff = 0.05, group="fish_type",
                      kw_cutoff = 0.05, multigrp_strat = TRUE, lda_cutoff=5)
plot_ef_bar(mm_lefse, label_level=2) +
  scale_fill_manual(values = c("#56B4E9","#D55E00"))
mm_lefse <- run_lefse(normld_salmon_t.Juvenile.F, wilcoxon_cutoff = 0.05, group="BKD_vaccinated",
                      kw_cutoff = 0.05, multigrp_strat = TRUE, lda_cutoff=5)
plot_ef_bar(mm_lefse, label_level=0) +
  scale_fill_manual(values = c("#56B4E9","#D55E00"))
mm_lefse@marker_table

# lefser package
# Life stage, Family level
normld_salmon_t <- phyloseq(otu_table(t(otu_table(normld_salmon))), tax_table(normld_salmon), sample_data(normld_salmon))
LL <- 1:nrow(normld_salmon_t@tax_table)
for(i in LL){
  if(is.na(normld_salmon_t@tax_table[i,2])){
    normld_salmon_t@tax_table[i,5] <- paste0("unclassified ","Bacteria"," lineage")
    normld_salmon_t@tax_table[i,4] <- c("unclassified Pylum")
    normld_salmon_t@tax_table[i,3] <- c("unclassified Phylum")
  }else{
    if(is.na(normld_salmon_t@tax_table[i,3])){
      normld_salmon_t@tax_table[i,5] <-  paste0("unclassified ",normld_salmon_t@tax_table[i,2]," lineage")
      normld_salmon_t@tax_table[i,4] <-  c("unclassified Class")
      
    }else{
      if(is.na(normld_salmon_t@tax_table[i,4])){
        normld_salmon_t@tax_table[i,5] <-  paste0("unclassified ",normld_salmon_t@tax_table[i,3]," lineage")
        
      }else{
        if(is.na(normld_salmon_t@tax_table[i,5])){
          normld_salmon_t@tax_table[i,5] <-  paste0("unclassified ",normld_salmon_t@tax_table[i,4]," lineage")
        }
      }
    }
  }
}
normld_salmon_t.F <- tax_glom(normld_salmon_t, NArm=FALSE, taxrank = "Family")
A_J <- phyloseq_to_deseq2(normld_salmon_t.F , ~ fish_type)
set.seed(1234)
res <- lefser(A_J, groupCol="fish_type")
res$Names <- normld_salmon_t.F@tax_table[res$Names,5]
head(res)
paste(res[res$scores>0,]$Names,collapse = ", ")
paste(res[res$scores<0,]$Names,collapse = ", ")
groupf <- colData(A_J)[["fish_type"]]
groupf <- as.factor(groupf)
groupsf <- levels(groupf)
.numeric01 <- function(x) {
  x <- as.factor(x)
  uvals <- levels(x)
  ifelse(x == uvals[1L], 0L, 1L)
}
group <- .numeric01(groupf)
lefse_plot1 <- lefserPlot(res) + 
  labs(fill="Fish Type",title="Family") + 
  scale_fill_manual(values = c("#56B4E9","#D55E00"), labels=c("Adult","Sub-adult"))

# Life stage, Genus level
normld_salmon_t.G <- tax_glom(normld_salmon_t,NArm=TRUE, taxrank = "Genus")
A_J <- phyloseq_to_deseq2(normld_salmon_t.G , ~ fish_type)
set.seed(1234)
res <- lefser(A_J, groupCol="fish_type")
res$Names <- normld_salmon_t.G@tax_table[res$Names,6]
head(res)
paste(res[res$scores>0,]$Names,collapse = ", ")
paste(res[res$scores<0,]$Names,collapse = ", ")
groupf <- colData(A_J)[["fish_type"]]
groupf <- as.factor(groupf)
groupsf <- levels(groupf)
group <- .numeric01(groupf)
lefse_plot2 <- lefserPlot(res) + 
  labs(fill="Fish Type", title="Genus") + 
  scale_fill_manual(values=c("#56B4E9","#D55E00"), labels=c("Adult","Sub-adult"))

# Vaccinated, Family level
normld_salmon_t <- phyloseq(otu_table(t(otu_table(normld_salmon))), tax_table(normld_salmon), sample_data(normld_salmon))
normld_salmon_t.Juvenile <- subset_samples(normld_salmon_t, fish_type=="Juvenile")
normld_salmon_t.Juvenile <- prune_taxa(taxa_sums(normld_salmon_t.Juvenile)>0, normld_salmon_t.Juvenile)
LL <- 1:nrow(normld_salmon_t.Juvenile@tax_table)
for(i in LL){
  if(is.na(normld_salmon_t.Juvenile@tax_table[i,2])){
    normld_salmon_t.Juvenile@tax_table[i,5] <- paste0("unclassified ","Bacteria"," lineage")
    normld_salmon_t.Juvenile@tax_table[i,4] <- c("unclassified Pylum")
    normld_salmon_t.Juvenile@tax_table[i,3] <- c("unclassified Phylum")
  }else{
    if(is.na(normld_salmon_t.Juvenile@tax_table[i,3])){
      normld_salmon_t.Juvenile@tax_table[i,5] <-  paste0("unclassified ",normld_salmon_t.Juvenile@tax_table[i,2]," lineage")
      normld_salmon_t.Juvenile@tax_table[i,4] <-  c("unclassified Class")
      
    }else{
      if(is.na(normld_salmon_t.Juvenile@tax_table[i,4])){
        normld_salmon_t.Juvenile@tax_table[i,5] <-  paste0("unclassified ",normld_salmon_t.Juvenile@tax_table[i,3]," lineage")
        
      }else{
        if(is.na(normld_salmon_t.Juvenile@tax_table[i,5])){
          normld_salmon_t.Juvenile@tax_table[i,5] <-  paste0("unclassified ",normld_salmon_t.Juvenile@tax_table[i,4]," lineage")
        }
      }
    }
  }
}
normld_salmon_t.Juvenile.F <- tax_glom(normld_salmon_t.Juvenile, NArm=FALSE, taxrank = "Family")
N_Y <- phyloseq_to_deseq2(normld_salmon_t.Juvenile.F , ~ BKD_vaccinated)
set.seed(1234)
res <- lefser(N_Y, groupCol="BKD_vaccinated")
res$Names <- normld_salmon_t.Juvenile.F@tax_table[res$Names,5]
head(res)
paste(res[res$scores>0,]$Names,collapse = ", ")
paste(res[res$scores<0,]$Names,collapse = ", ")
groupf <- colData(N_Y)[["BKD_vaccinated"]]
groupf <- as.factor(groupf)
groupsf <- levels(groupf)
group <- .numeric01(groupf)
lefse_plot3 <- lefserPlot(res) + 
  labs(fill="Sub-adult BKD\nVaccination Status", title="Family") + 
  scale_fill_manual(values=c("#56B4E9","#D55E00"), labels = c("No","Yes")) 

# Vaccinated, Genus level
normld_salmon_t.Juvenile.F <- tax_glom(normld_salmon_t.Juvenile, NArm=FALSE, taxrank="Genus")
N_Y <- phyloseq_to_deseq2(normld_salmon_t.Juvenile.F, ~ BKD_vaccinated)
set.seed(1234)
res <- lefser(N_Y, groupCol="BKD_vaccinated")
res$Names <- normld_salmon_t.Juvenile.F@tax_table[res$Names,6]
head(res)
paste(res[res$scores>0,]$Names, collapse = ", ")
paste(res[res$scores<0,]$Names, collapse = ", ")
groupf <- colData(N_Y)[["BKD_vaccinated"]]
groupf <- as.factor(groupf)
groupsf <- levels(groupf)
group <- .numeric01(groupf)
lefse_plot4 <- lefserPlot(res) + 
  labs(fill="Sub-adult BKD\nVaccination Status",title="Genus") + 
  scale_fill_manual(values = c("#56B4E9","#D55E00"),labels = c("No","Yes")) 
lefse_plots1 <- ggarrange(lefse_plot1, lefse_plot2, legend="right", common.legend=TRUE, align="v")
# ggsave("Figures/lefse_plots1.pdf", plot=lefse_plots1, width=9.0, height=4.0)
lefse_plots2 <- ggarrange(lefse_plot3, lefse_plot4, legend="right", common.legend=TRUE, align="v")
# ggsave("Figures/lefse_plots2.pdf", plot=lefse_plots2, width=9.0, height=4.0)


#########################################################################################
######################## Core families, vacc/unvacc ####################################
#########################################################################################

### Sub-adults
normld_salmon.Juvenile <- subset_samples(normld_salmon,fish_type=="Juvenile")
normld_salmon.Juvenile <- subset_samples(normld_salmon.Juvenile,BKD_vaccinated=="Y")
normld_salmon.Juvenile <- prune_taxa(taxa_sums(normld_salmon.Juvenile)>0, normld_salmon.Juvenile)

### Prevalence distribution: number of samples a taxon occurs in
### ASV
ASV_prevalence_Juvenile <- as.data.frame(apply(as.data.frame(t(as.data.frame(normld_salmon.Juvenile@otu_table))),1,function(x) sum(x>0)))
colnames(ASV_prevalence_Juvenile) <- c("prevalence")
ASV_prevalence_Juvenile_ord <- as.data.frame(ASV_prevalence_Juvenile[order(ASV_prevalence_Juvenile$prevalence,decreasing = TRUE),])
colnames(ASV_prevalence_Juvenile_ord) <- c("prevalence")
countASVs_prevalence_Juvenile <- as.data.frame(table(ASV_prevalence_Juvenile_ord))
colnames(countASVs_prevalence_Juvenile) <- c("prevalence","frequency")
ASV_prevalence_Juvenile_ord$prevalence <- 100*ASV_prevalence_Juvenile_ord$prevalence/nsamples(normld_salmon.Juvenile)
J_ASV_plot <- ggplot(ASV_prevalence_Juvenile_ord,aes(prevalence)) + geom_vline(xintercept=80, linetype="dashed") +
  geom_bar()+labs(title="ASV") + scale_y_continuous(name ="Number of ASVs") + 
  scale_x_continuous(name ="Prevalence (% of samples)", limit = c(0, 105)) + 
  theme(title=element_text(size=12), legend.position="none")
J_ASV_plot

### Genus
normld_salmon.Juvenile.G <- tax_glom(normld_salmon.Juvenile, NArm=FALSE, taxrank="Genus")
G_prevalence_Juvenile <- as.data.frame(apply(as.data.frame(t(as.data.frame(normld_salmon.Juvenile.G@otu_table))), 1, function(x) sum(x>0)))
colnames(G_prevalence_Juvenile) <- c("prevalence")
G_prevalence_Juvenile_ord <- as.data.frame(G_prevalence_Juvenile[order(G_prevalence_Juvenile$prevalence,decreasing = TRUE),])
colnames(G_prevalence_Juvenile_ord) <- c("prevalence")
countGs_prevalence_Juvenile <- as.data.frame(table(G_prevalence_Juvenile_ord))
colnames(countGs_prevalence_Juvenile) <- c("prevalence","frequency")
G_prevalence_Juvenile_ord$prevalence <- 100*G_prevalence_Juvenile_ord$prevalence/nsamples(normld_salmon.Juvenile.G)
J_Genus_plot <- ggplot(G_prevalence_Juvenile_ord,aes(prevalence)) + geom_vline(xintercept=80, linetype="dashed") + 
  geom_bar()+labs(title="Genus") + scale_y_continuous(name ="Number of genera") + 
  scale_x_continuous(name ="Prevalence (% of samples)", limit = c(0, 105)) + 
  theme(title=element_text(size=12), legend.position="none")
J_Genus_plot

### Family
normld_salmon.Juvenile.F <- tax_glom(normld_salmon.Juvenile, NArm=FALSE, taxrank="Family")
F_prevalence_Juvenile <- as.data.frame(apply(as.data.frame(t(as.data.frame(normld_salmon.Juvenile.F@otu_table))), 1, function(x) sum(x>0)))
colnames(F_prevalence_Juvenile) <- c("prevalence")
F_prevalence_Juvenile_ord <- as.data.frame(F_prevalence_Juvenile[order(F_prevalence_Juvenile$prevalence,decreasing=TRUE),])
colnames(F_prevalence_Juvenile_ord) <- c("prevalence")
countFs_prevalence_Juvenile <- as.data.frame(table(F_prevalence_Juvenile_ord))
colnames(countFs_prevalence_Juvenile) <- c("prevalence","frequency")
F_prevalence_Juvenile_ord$prevalence <- 100*F_prevalence_Juvenile_ord$prevalence/nsamples(normld_salmon.Juvenile.F)
J_Family_plot <- ggplot(F_prevalence_Juvenile_ord,aes(prevalence)) + geom_vline(xintercept=80, linetype="dashed") + 
  geom_bar()+labs(title="Family") + scale_y_continuous(name ="Number of families") + 
  scale_x_continuous(name ="Prevalence (% of samples)", limit = c(0, 105)) + 
  theme(title=element_text(size=12), legend.position="none")
J_Family_plot

plot9 <- ggarrange(J_ASV_plot, J_Genus_plot, J_Family_plot, nrow=3, ncol = 1, align="v")
plot9
# ggsave("Figures/prevalence_juveniles_vacc.pdf", plot=plot9, width=4, height=10)

### Prevalence - average relative abundance

### ASV
normld_salmon.Juvenile.ReAb <- transform_sample_counts(normld_salmon.Juvenile, function(OTU) OTU*100/sum(OTU))
ASV_sumReAb_Juvenile <- as.data.frame(taxa_sums(normld_salmon.Juvenile.ReAb))
ASV_sumReAb_Juvenile$otu <- rownames(ASV_sumReAb_Juvenile)
colnames(ASV_sumReAb_Juvenile) <- c("sumReAb","otu")
ASV_sumReAb_Juvenile$mReAb <- ASV_sumReAb_Juvenile$sumReAb/nsamples(normld_salmon.Juvenile.ReAb)
ASV_prevalence_Juvenile$OTU <- rownames(ASV_prevalence_Juvenile)
ASV_prevalence_mReAb_Juvenile <- merge(ASV_prevalence_Juvenile,ASV_sumReAb_Juvenile,by.x="OTU",by.y="otu",all.x = TRUE,sort = FALSE)
ASV_prevalence_mReAb_Juvenile_ord <- ASV_prevalence_mReAb_Juvenile[order(ASV_prevalence_mReAb_Juvenile$prevalence),]
ASV_prevalence_mReAb_Juvenile_ord$prevalence <- 100*ASV_prevalence_mReAb_Juvenile_ord$prevalence/nsamples(normld_salmon.Juvenile.ReAb)
mod <- lm(mReAb ~ prevalence, data=ASV_prevalence_mReAb_Juvenile_ord)
summary(mod)$coefficient
summary(mod)$r.squared
df <- data.frame(p=c(NA,NA,NA),r=c(NA,NA,NA),row.names = c("Family","Genus","ASV"))
df[3,1] <- summary(mod)$coefficient[2,4]
df[3,2] <- summary(mod)$r.squared
ggplot(ASV_prevalence_mReAb_Juvenile_ord, aes(x=prevalence, y=mReAb)) + 
  geom_point(size=3,shape=1) + labs(x="Prevalence (% of samples)", y="Average relative abundance (%)") + 
  theme(axis.text=element_text(size=12), axis.title=element_text(size=14))

### Genus
normld_salmon.Juvenile.ReAb.G <- transform_sample_counts(normld_salmon.Juvenile.G, function(OTU) OTU*100/sum(OTU))
G_sumReAb_Juvenile <- as.data.frame(taxa_sums(normld_salmon.Juvenile.ReAb.G))
G_sumReAb_Juvenile$otuG <- rownames(G_sumReAb_Juvenile)
colnames(G_sumReAb_Juvenile) <- c("sumReAb","otuG")
G_sumReAb_Juvenile$mReAb <- G_sumReAb_Juvenile$sumReAb/nsamples(normld_salmon.Juvenile.ReAb.G)
G_prevalence_Juvenile$OTUG <- rownames(G_prevalence_Juvenile)
G_prevalence_mReAb_Juvenile <- merge(G_prevalence_Juvenile,G_sumReAb_Juvenile,by.x="OTUG",by.y="otuG",all.x = TRUE,sort = FALSE)
G_prevalence_mReAb_Juvenile_ord <- G_prevalence_mReAb_Juvenile[order(G_prevalence_mReAb_Juvenile$prevalence),]
G_prevalence_mReAb_Juvenile_ord$prevalence <- 100*G_prevalence_mReAb_Juvenile_ord$prevalence/nsamples(normld_salmon.Juvenile.ReAb.G)
mod <- lm(mReAb~prevalence,data=G_prevalence_mReAb_Juvenile_ord)
summary(mod)$coefficient
summary(mod)$r.squared
df[2,1] <- summary(mod)$coefficient[2,4]
df[2,2] <- summary(mod)$r.squared
ggplot(G_prevalence_mReAb_Juvenile_ord, aes(x=prevalence, y=mReAb)) + 
  geom_point(size=3,shape=1) + labs(x="Prevalence (% of samples)", y="Average relative abundance (%)") + 
  theme(axis.text=element_text(size=12), axis.title=element_text(size=14))

### Family
normld_salmon.Juvenile.ReAb.F <- transform_sample_counts(normld_salmon.Juvenile.F, function(OTU) OTU*100/sum(OTU))
F_sumReAb_Juvenile <- as.data.frame(taxa_sums(normld_salmon.Juvenile.ReAb.F))
F_sumReAb_Juvenile$otuF <- rownames(F_sumReAb_Juvenile)
colnames(F_sumReAb_Juvenile) <- c("sumReAb","otuF")
F_sumReAb_Juvenile$mReAb <- F_sumReAb_Juvenile$sumReAb/nsamples(normld_salmon.Juvenile.ReAb.F)
F_prevalence_Juvenile$OTUF <- rownames(F_prevalence_Juvenile)
F_prevalence_mReAb_Juvenile <- merge(F_prevalence_Juvenile,F_sumReAb_Juvenile,by.x="OTUF",by.y="otuF",all.x = TRUE,sort = FALSE)
F_prevalence_mReAb_Juvenile_ord <- F_prevalence_mReAb_Juvenile[order(F_prevalence_mReAb_Juvenile$prevalence),]
F_prevalence_mReAb_Juvenile_ord$prevalence <- 100*F_prevalence_mReAb_Juvenile_ord$prevalence/nsamples(normld_salmon.Juvenile.ReAb.F)
ggplot(F_prevalence_mReAb_Juvenile_ord,aes(x=prevalence,y=mReAb))+geom_point(size=3,shape=1)+labs(x="Prevalence (%)",y="Average relative abundance (%)")+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(),axis.text.y = element_text(size=12),axis.text.x = element_text(size=12))
length(F_prevalence_mReAb_Juvenile_ord$OTUF[F_prevalence_mReAb_Juvenile_ord$prevalence>=80])
sum(normld_salmon.Juvenile.F@otu_table[,F_prevalence_mReAb_Juvenile_ord$OTUF[F_prevalence_mReAb_Juvenile_ord$prevalence>=80]])/sum(normld_salmon.Juvenile.F@otu_table)
mod <- lm(mReAb~prevalence,data=F_prevalence_mReAb_Juvenile_ord)
summary(mod)$coefficient
summary(mod)$r.squared
df[1,1] <- summary(mod)$coefficient[2,4]
df[1,2] <- summary(mod)$r.squared
ggplot(F_prevalence_mReAb_Juvenile_ord, aes(x=prevalence, y=mReAb)) + 
  geom_point(size=3,shape=1) + labs(x="Prevalence (% of samples)", y="Average relative abundance (%)") + 
  theme(axis.text=element_text(size=12), axis.title=element_text(size=14)) + xlim(0,100)

### Juvenile core ASV/Genus/Family averageReAb bar plot with prevalence line overlaid 

### ASV
rownames(ASV_prevalence_mReAb_Juvenile_ord) <- ASV_prevalence_mReAb_Juvenile_ord$OTU
ASV_core <- ASV_prevalence_mReAb_Juvenile_ord[ASV_prevalence_mReAb_Juvenile_ord$OTU[ASV_prevalence_mReAb_Juvenile_ord$prevalence>=80],]
ASV_core_ord <- ASV_core[order(ASV_core$mReAb),]
ASV_core_taxa <- as.data.frame(normld_salmon.Juvenile.ReAb@tax_table[ASV_core_ord$OTU,])
ASV_core_taxa$otu <- rownames(ASV_core_taxa)
plot_ASVcore <- merge(ASV_core_ord,ASV_core_taxa,by.x="OTU",by.y="otu",all.x = TRUE,sort = FALSE)
# write_xlsx(plot_ASVcore,"/Users/linglab/Documents/salmon_m/table_S4C")

### Genus
rownames(G_prevalence_mReAb_Juvenile_ord) <- G_prevalence_mReAb_Juvenile_ord$OTUG
G_core <- G_prevalence_mReAb_Juvenile_ord[G_prevalence_mReAb_Juvenile_ord$OTUG[G_prevalence_mReAb_Juvenile_ord$prevalence>=80],]
G_core_ord <- G_core[order(G_core$mReAb),]
G_core_taxa <- as.data.frame(normld_salmon.Juvenile.ReAb.G@tax_table[G_core_ord$OTUG,])
G_core_taxa$classification <- rep("genus",nrow(G_core_taxa))
LL <- 1:nrow(G_core_taxa)
for(i in LL){
  if(is.na(G_core_taxa$Phylum[i])){
    G_core_taxa$classification[i] <- paste0("unclassified ","Bacteria"," lineage")
  }else{
    if(is.na(G_core_taxa$Class[i])){
      G_core_taxa$classification[i] <-  paste0("unclassified ",G_core_taxa$Phylum[i]," lineage")
    }else{
      if(is.na(G_core_taxa$Order[i])){
        G_core_taxa$classification[i] <-  paste0("unclassified ",G_core_taxa$Class[i]," lineage")
      }else{
        if(is.na(G_core_taxa$Family[i])){
          G_core_taxa$classification[i] <-  paste0("unclassified ",G_core_taxa$Order[i]," lineage")
        }else{
          if(is.na(G_core_taxa$Genus[i])){
            G_core_taxa$classification[i] <-  paste0("unclassified ",G_core_taxa$Family[i]," lineage")
          }else{
            G_core_taxa$classification[i] <- G_core_taxa$Genus[i]
          }
        }
      }
    }
  }
}
G_core_taxa$otuG <- rownames(G_core_taxa)
plot_Gcore <- merge(G_core_ord, G_core_taxa[,c("otuG","classification")], 
                    by.x="OTUG", by.y="otuG", all.x = TRUE,sort = FALSE)
# write_xlsx(plot_Gcore,"/Users/linglab/Documents/salmon_m/table_S4B")

### Family
rownames(F_prevalence_mReAb_Juvenile_ord) <- F_prevalence_mReAb_Juvenile_ord$OTUF
F_core <- F_prevalence_mReAb_Juvenile_ord[F_prevalence_mReAb_Juvenile_ord$OTUF[F_prevalence_mReAb_Juvenile_ord$prevalence>=80],]
F_core_ord <- F_core[order(F_core$mReAb),]
F_core_taxa <- as.data.frame(normld_salmon.Juvenile.ReAb.F@tax_table[F_core_ord$OTUF,])
F_core_taxa$classification <- rep("family",nrow(F_core_taxa))
LL <- 1:nrow(F_core_taxa)
for(i in LL){
  if(is.na(F_core_taxa$Phylum[i])){
    F_core_taxa$classification[i] <- paste0("unclassified ","Bacteria"," lineage")
  }else{
    if(is.na(F_core_taxa$Class[i])){
      F_core_taxa$classification[i] <-  paste0("unclassified ",F_core_taxa$Phylum[i]," lineage")
    }else{
      if(is.na(F_core_taxa$Order[i])){
        F_core_taxa$classification[i] <-  paste0("unclassified ",F_core_taxa$Class[i]," lineage")
      }else{
        if(is.na(F_core_taxa$Family[i])){
          F_core_taxa$classification[i] <-  paste0("unclassified ",F_core_taxa$Order[i]," lineage")
        }else{
          F_core_taxa$classification[i] <- F_core_taxa$Family[i]
        }
      }
    }
  }
}
F_core_taxa$otuF <- rownames(F_core_taxa)
plot_Fcore <- merge(F_core_ord, F_core_taxa[,c("otuF","classification")], 
                    by.x="OTUF", by.y="otuF", all.x=TRUE, sort=FALSE)
Fabund <- ggplot(plot_Fcore) + geom_bar(aes(x=reorder(classification,mReAb), 
                                            y=mReAb,color="Abundance"), stat="identity", fill="grey") +
  labs(x="Core family") + coord_flip() + scale_y_continuous(name="Average relative\nabundance (%)") +
  theme(legend.position="none", panel.grid.minor=element_blank(),
        axis.text.y=element_text(face="italic",size=10), axis.text.x=element_text(hjust=0,size=10)) +
  scale_color_manual(name=NULL, values=c("Abundance"="grey","Prevalence"="black","Prevalence"="black"))
Fprev <- ggplot(plot_Fcore) + geom_line(aes(x=reorder(classification, mReAb), y=prevalence, group=1)) +
  geom_point(aes(x=reorder(classification,mReAb), y=prevalence)) +
  coord_flip() + scale_y_continuous(name="Prevalence\n(% of samples)", limits=c(70,100)) +
  theme(legend.position="none", axis.text.y=element_blank(), panel.grid.minor=element_blank(), 
        axis.ticks.y=element_blank(), axis.title.y=element_blank())
# write_xlsx(plot_Fcore,"/Users/linglab/Documents/salmon_m/table_S4A")
PrevAbundJuv_NonVacc <- ggarrange(Fabund,Fprev, widths = c(4, 1))
# ggsave("Figures/prevalence_abund_juveniles_nonvacc.pdf", plot=PrevAbundJuv_NonVacc, width=5, height=8)


